apiVersion: v1
kind: Service
metadata:
  name: demo-ts-app
  namespace: default
  labels:
    app: demo-ts-app
spec:
  selector:
    app: demo-ts-app
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  type: ClusterIP